[package]
name = "topoi-core"
version = "0.1.0"
authors = ["zypeh <zypeh.geek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec = "1.2.0"